version: "3"

services:
  server:
    restart: always
    env_file:
      - ./server/.env
    build: ./server
    image: server
    ports: 
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      # - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - server
    networks:
      - app-network

  mongodb:
    restart: always
    image: "mongo"
    container_name: 'mongodb'
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
  
networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  # web-root:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /root/simple-crud-go-mongo/
  #     o: bind