version: "3"

services:
  server:
    restart: always
    build: ./server
    image: server
    ports: 
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    restart: always
    image: "mongo"
    container_name: 'mongodb'
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db 
  
networks:
  app-network:
    driver: bridge